### ISSUE TITLE
Bit rate switching (BRS bit) support

### ISSUE THREAD

**Issue by MaratSabitov** [intrepidcs/intrepid-socketcan-kernel-module#12]
Does driver support the bit rate switching for CAN FD?
I mean support for switching the standard bit rate of the ARBITRATION PHASE to the preconfigured alternate bit rate of the
DATA PHASE, based on BRS bit value.

**Comment by hollinsky-intrepid** [comment]
Yes, that would be the `CANFD_BRS` flag in the SocketCAN message, and we fully support it. If it is set on a CAN FD message, the alternate bit rate will be used. Otherwise, the FDF bit will be set but the standard bit rate will be used for the data phase.

This flag is also set on messages being received if the data phase used the FD bit rate.

Let us know if there's anything else we can help with!
